[package]
name = "embedded-ci-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.13.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
uuid = { version = "1.5", features = ["v4", "serde"] }

[dev-dependencies]
serde_json = "1.0"
