[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true

[default.reset]
enabled = true

[default.general]
chip = "STM32F411RETx"
connect_under_reset = false

[default.rtt]
enabled = true
channels = [
    { up = 0, down = 0, name = "rtt", format = "String" },

    # { up = 0, name = "defmt_name", format = "Defmt" },
]
timeout = 3000
show_timestamps = true
log_enabled = false
log_path = "./logs"

[default.gdb]
# Whether or not a GDB server should be opened after flashing.
enabled = false
